### PR TITLE
Update dominikh's unused, staticcheck and gosimple paths to go-tools

### LINKED ISSUE #257: Linter staticcheck has moved to new repo
The linter `staticcheck` from the README.md has moved to https://github.com/dominikh/go-tools

### PR DESCRIPTION
**Pull request by bradleyfalzon**
As mentioned on:

- https://github.com/dominikh/go-unused
- https://github.com/dominikh/go-staticcheck
- https://github.com/dominikh/go-simple

Closes #257.
Updates #247.

### CODE REVIEW

**Comment by bradleyfalzon** [comment]
The first few commits are my fault, but the last commit I needed my local tests to fail to have CI's pass.

When I run the tests locally I get TestSafesql fail as well as a column difference:

```
ok      github.com/alecthomas/gometalinter      0.003s [no tests to run]
--- FAIL: TestSafesql (0.98s)
        Error Trace:    support.go:89
                        safesql_test.go:36
        Error:          Not equal: regressiontests.Issues{regressiontests.Issue{Linter:"safesql", Severity:"warning", Path:"test.go", Line:20, Col:23, Message:"potentially unsafe SQL statement"}} (expected)
                                != regressiontests.Issues{} (actual)

                        Diff:
                        --- Expected
                        +++ Actual
                        @@ -1,3 +1,2 @@
                        -(regressiontests.Issues) (len=1 cap=1) {
                        - (regressiontests.Issue) test.go:20:23:warning: potentially unsafe SQL statement (safesql)
                        +(regressiontests.Issues) {
                         }

--- FAIL: TestStaticCheck (1.27s)
        Error Trace:    support.go:89
                        staticcheck_test.go:16
        Error:          Not equal: regressiontests.Issues{regressiontests.Issue{Linter:"staticcheck", Severity:"warning", Path:"test.go", Line:5, Col:27, Message:"error parsing regexp: missing argument to repetition operator: `*` (SA1000)"}} (expected)
                                != regressiontests.Issues{regressiontests.Issue{Linter:"staticcheck", Severity:"warning", Path:"test.go", Line:5, Col:28, Message:"error parsing regexp: missing argument to repetition operator: `*` (SA1000)"}} (actual)

                        Diff:
                        --- Expected
                        +++ Actual
                        @@ -1,3 +1,3 @@
                         (regressiontests.Issues) (len=1 cap=1) {
                        - (regressiontests.Issue) test.go:5:27:warning: error parsing regexp: missing argument to repetition operator: `*` (SA1000) (staticcheck)
                        + (regressiontests.Issue) test.go:5:28:warning: error parsing regexp: missing argument to repetition operator: `*` (SA1000) (staticcheck)
                         }

FAIL
FAIL    github.com/alecthomas/gometalinter/regressiontests      6.162s
```

I may not have used `gvt` correctly?

**Comment by alecthomas** [comment]
Hmm. staticcheck seems to be a LOT slower than it used to be.

**Comment by alecthomas** [comment]
Here's a comparison:

```
[aat@cavern:~/Projects/kingpin]time staticcheck .
staticcheck .  0.16s user 0.02s system 171% cpu 0.105 total
[aat@cavern:~/Projects/kingpin]time staticcheck .
staticcheck .  9.52s user 1.22s system 381% cpu 2.820 total
```

**Comment by bradleyfalzon** [comment]
Yeah I saw your thread, of all the checks gometalinter runs by default, staticcheck is a very important one, the issues it finds are almost certainly problems - i.e. they're not optimisations and there's few false positives.

The recent changes have made it slower, but I do hope you still see the value in making it a default.

**Comment by alecthomas** [comment]
All three tools are much slower now. Running them over a large codebase is going to increase the runtime significantly.

**Comment by alecthomas** [comment]
I added them to the [slow linters list](8747b3f8d7af209a05841d9e07ea32be6044e01e), so at least if people are using `--fast` they won't be surprised. I have another change that should improve performance when using `...`, which should also help significantly.

**Comment by bradleyfalzon** [comment]
That sounds good, keep them enabled by default really does help newcomers too, and if you're running across a large project, you may have a better understanding of the tools to be more selective when and which you run.

**Pull request merged**
