### PR TITLE
vendor: update errcheck

### PR DESCRIPTION
**Pull request by powerman**
Reason for upgrade explained in #198.

I've added all files, including optional ones (tests, README) - these may be removed if you like.

### CODE REVIEW

**Comment by alecthomas** [comment]
Sorry to mess you around, but can you please use [gvt](https://github.com/FiloSottile/gvt) to update the vendored code? It is largely automatic: `gvt update <package>`. This is my fault; I thought I had documented this in the README.

**Comment by powerman** [comment]
Sure, I'll update the PR now.

**Comment by powerman** [comment]
Done. But I'm not sure is it ok to not include https://github.com/kisielk/gotool/blob/master/LEGAL

**Comment by alecthomas** [comment]
Not ideal, but we can add it in if someone complains. Thanks!

PS. I've updated the [CONTRIBUTING](https://github.com/alecthomas/gometalinter/blob/master/CONTRIBUTING.md) file with instructions for gvt.

**Pull request merged**
