### PR TITLE
Add linter lll

### PR DESCRIPTION
**Pull request by walle**
This commit adds lll (Line Length Linter) (https://github.com/walle/lll)

### CODE REVIEW

**Comment by alecthomas** [comment]
I'm not opposed to this, but there are a couple of problems:

1.

**Comment by walle** [comment]
I've fixed number one and two, in the latest commit.
Regarding number tree, the vendor dir is skipped by default, like in dupl (https://github.com/mibk/dupl) and can be included by using the `--vendor` flag.

**Comment by alecthomas** [comment]
Thanks!

gometalinter explicitly uses `dupl ./*.go` to prevent it recursing. I've also had to fork gocyclo to do the same. It's not specifically about the "vendor" directory, but more about total directory size. Data files, etc.

That said, it looks like `lll` can be run with wildcards, so if you can also change the line to `lll -g -l {maxlinelength} ./*.go` I'll merge it in.

**Comment by walle** [comment]
No, it couldn't do that. But I have updated the project to support this, since it's a good feature.

Ok, I'll change this, should I squash my commits before you merge?

**Comment by alecthomas** [comment]
Perfect. Yes, please, squashing would be great.

**Comment by walle** [comment]
Great, squashed them into dcbd029

**Comment by alecthomas** [comment]
Thanks!

**Comment by alecthomas** [comment]
FYI I've disabled it by default, as it's very chatty at 80 characters. It can be explicitly enabled with `--enable=lll`

**Comment by walle** [comment]
Aha, ok. I saw that you added some documentation in the readme, I just realised that I had missed that, great.

**Pull request merged**
