### PR TITLE
vendor: update golint

### PR DESCRIPTION
**Pull request by fsouza**
To get new context.Context related linting.

### CODE REVIEW

**Comment by alecthomas** [comment]
Thanks!

**Comment by ramya-rao-a** [comment]
@alecthomas with this change `gometalinter` can no longer support Go1.5 . See https://github.com/golang/lint/issues/246

Is it possible to not have `golint` as one of the linters installed as part of `gometalinter` when go version is < 1.6?

**Comment by alecthomas** [comment]
Unfortunately this has always been a problem. Most of the tools depend on go/types, which breaks often when new Go versions are released. I'm actually a bit surprised it still works on Go 1.5.

I don't think conditionally using an external golint is a good option though; that way lies madness. I am not sure what the right solution is though, perhaps using gopkg.in and mirror Go's versions. If I create branches for 1.5, 1.6, 1.7, and so on. That will, however, mean that the binaries will be called gometalinter.v5, gometalinter.v6, and so on.

Thoughts?

**Comment by ramya-rao-a** [comment]
Am not sure what you meant by using an "external golint"

If we go the gopkg.in way like you described, that would send a weird message that gometalinter itself is in major version 5/6/7 which might not be a good idea.

Since `golint` has officially dropped support for Go1.5.*, I was hoping to drop `golint` from the list of linters used by `gometalinter` based on the Go version which you can get by `runtime.Version`

**Comment by alecthomas** [comment]
Ah, I see what you're saying. Sure, that sounds fine to me. I thought you were suggesting using the vendored golint when > 1.5 and a non-vendored (external) golint when <= 1.5.

**Pull request merged**
