### PR TITLE
Replace deadline crutch again

### PR DESCRIPTION
**Pull request by dnephin**
Take 2 of #288, sorry about take 1.
I left the changes in a separate commit so it's easier to see what has changed. 

Testing manually with a deadline, I can see the correct value is printed. I've also added a test to cover the case that was broke by take 1.

### CODE REVIEW

**Comment by alecthomas** [comment]
How's this PR looking?

**Comment by dnephin** [comment]
I was able to manually verify that the previous bug was fixed, but I don't have a test for it.

I'm not sure why the test (in the description) is giving me the default value instead of the flag value. My suspicious is that I'm missing something about how kingpin works.

**Comment by dnephin** [comment]
Ok, I fixed the test. I changed `init()` to be `setupFlags(app)`, and in `main()` I pass in `kingpin.CommandLine` as the app. In the test I create a new app, add the flags, and the test passes.

This is ready for review.

**Comment by alecthomas** [comment]
Thanks!

**Pull request merged**
