### PR TITLE
Add an `include` flag to only include certain messages

### PR DESCRIPTION
**Pull request by svanharmelen**
By adding this option, editors have a way to run `gometalinter` and only output the results for the file being saved. Of course it also helps other use cases where you only want to check if a specific error/warning is triggered by your code.

Tested this with a customised version of `vim-go` (will make a PR there as well to use this new functionality) and it works really well.

### CODE REVIEW

**Comment by svanharmelen** [comment]
@alecthomas any thoughts or feedback would be great! Thx!

**Comment by alecthomas** [comment]
Thanks!

**Comment by svanharmelen** [comment]
:+1:

**Comment by alecthomas** [comment]
Note that the short flag for this has been changed to `-I`. It was conflicting with the short flag for `--install`.

**Pull request merged**
