### PR TITLE
Replace testify with gotestyourself/assert

### PR DESCRIPTION
**Pull request by dnephin**
I've been a user of `testify` for a while, however I've noticed it is not really maintained anymore and there are still a [lot of things I'd like to change](https://github.com/test-go/testify/issues/13).

`gotestyourself/fs` is already in use in the test suite, so I was wondering if you would accept using the assertions as well. The interface is similar to testify, but it does try to fix some of the problems with the old interface. 

Comments on the interface are definitely welcome.

### CODE REVIEW

**Comment by alecthomas** [comment]
Architecturally, I like the separation between comparators and the check/assert functions. But as a consumer of the API I find it less convenient:

```go
assert.Equal(t, "/bin/custom", config.Command)
```
vs.
```go
assert.Check(t, is.Equal("/bin/custom", config.Command))
```

Purely for usability, that is less simple.

Could the `assert` package have a set of convenience functions around the most commonly used comparators?

eg. `gotestyourself/assert/convenience.go`

```go
func Equal(t *testing.T, a, b interface{}) {
  Assert(t, cmp.Equal(a, b))
}

// etc.
```

This would keep the flexibility of the API, but be more convenient for users. 99% of the time I do not want to continue the test if an assertion fails, so I think defaulting to `Assert()` is fine.

If these functions existed, I'd be happy to use gotestyourself. As you outline in https://github.com/test-go/testify/issues/13, there are a bunch of issues with testify. I even [forked it myself](https://github.com/alecthomas/assert) for similar reasons.

If you add these helper functions, can you apply the change to the v3-unstable branch? I'd like to avoid having to duplicate work on both branches from now on.

**Comment by alecthomas** [comment]
Also, for a bit of extra static typing it might be worth replacing `BoolOrComparison` with separate Assert/Check functions:

```
func Assert(t TestingT, comparison Comparison, msgAndArgs...interface{})
func True(t TestingT, truth bool, msgAndArgs...interface{})
func False(t TestingT, truth bool, msgAndArgs...interface{})
```

etc.

Maybe that's overkill given how dynamic the comparators themselves are though.

**Comment by alecthomas** [comment]
Another minor comment; it would be nice to use `expected, actual` as the comparator argument names (or `actual, expected`, I have no real preference) and use that in the output of test failures as testify does.

**Comment by dnephin** [comment]
> Could the assert package have a set of convenience functions around the most commonly used comparators?

Yup, in fact a couple already exist:
* [assert.Equal()](https://godoc.org/github.com/gotestyourself/gotestyourself/assert#Equal)
* [assert.NilError()](https://godoc.org/github.com/gotestyourself/gotestyourself/assert#NilError)

I think this should cover the 80% case. I'd like to wait on adding any more convenience functions for now, but it is always possible to add more later.

`assert.Equal()` isn't in this diff because I used gotestyourself/gotestyourself#36 to automate the migration, and it preserves the original behaviour. Since the code was using `assert.Equal()` it was translated to `Check`.

I can run the tool against the v3 branch instead.

>  for a bit of extra static typing it might be worth replacing BoolOrComparison with separate Assert/Check functions

Ya, that's also an option. I don't think I would add `assert.False()`, just `assert.True()` to accept a bool, and then Check/Assert would only accept comparators. However I suspect that in the future I may want to expand the Comparator interface to accept different types (either an interface, or a func that accepts arguments), so it would need to be `interface[}` to support that.

> it would be nice to use expected, actual as the comparator argument names 

I have a preference for `actual, expected`, but I left this out because it's so difficult (maybe impossible) to enforce. `Equal` and `Compare` could accept args in either order, and the message becomes confusing if someone puts them backwards. Since there is no way to enforce that the args are in the correct order,  I think it's better to just report left/right. 

It's possible that the assertion failure message could include the source code for the arguments, which would help debugging, but I haven't done that yet because I'm not sure it's necessary. Something like this:

```go
assert.Equal(t, 100, count)
// assertion failed: 100 (int) != 101 (count int)

assert.Equal(t, expected, count)
// assertion failed: 100 (expected int) != 101 (count int)
```

It would require that the Comparator function type accept extra arguments.

**Comment by dnephin** [comment]
If you are curious https://github.com/gotestyourself/gotestyourself/pull/47 adds the variable names of the arguments passed to `Equal` (like in the example above) to make the expected/actual values obvious from the failure message.

The argument names can still be changed to suggest a convention for the order, but I haven't done that yet.

**Comment by alecthomas** [comment]
Lets migrate v3-unstable to use gotestyourself.

**Pull request closed without merging**
