### PR TITLE
gometalinter.v1: Fix mvdan package paths for --install

### PR DESCRIPTION
**Pull request by cyphus**
Running `gometalinter.v1 --install` fails due to bad package paths for interfacer and unparam. This PR fixes the offending paths.

It appears that these packages are already being imported under the new path, but they are vendored under the old path in `_linters/`. I'm not sure how to update the vendored linters so I left that alone.

Side note: if interfacer and unparam are already vendored, do they need to be installed at all?

### CODE REVIEW

**Comment by cyphus** [comment]
It may be useful to have a `v1` branch to keep track of v1 releases. I had to target the master branch for this PR, but my branch is based off of v1.2.1.

**Comment by alecthomas** [comment]
You seem to be using a very *very* old version of gometalinter?

**Comment by cyphus** [comment]
My branch is one commit ahead of the `v1.2.1` tag, which is the latest gometalinter.v1 release.

What is the current level of support for v1? If it's not going to receive updates, I'll switch to v2.

**Comment by alecthomas** [comment]
v1 is unsupported, you should definitely switch to v2 👍

**Pull request closed without merging**
