### PR TITLE
Add dominikh's megacheck (staticcheck, gosimple and unused)

### PR DESCRIPTION
**Pull request by bradleyfalzon**
This is just a PR to discuss adding Megacheck in.

I've added this and testing it currently, appears to work as intended, but my testing does seem to indicate megacheck running in gometalinter is *faster* than megacheck running by itself - and it still shows the same results (so it's not doing less). See https://gist.github.com/bradleyfalzon/f7891db8e1d61ebe7dcef1deab6c6277 for some tests, I'm not sure what's different (even environment variables matched when checked via strace).

But other than that, it's working as intended and could be merged, but I'd like to know if others experience the same speed difference if someone can take a moment to check?

EDIT: This is ready to be merged, but currently keeps staticcheck, gosimple and unused. So people running `--enable-all` will duplicate the tools.

### CODE REVIEW

**Comment by alecthomas** [comment]
This is great, thanks.

What you're seeing is probably due to gometalinter setting `GOGC=off`. You can verify  this by running it with `--enable-gc`.

**Comment by bradleyfalzon** [comment]
Curiouser and curiouser, I thought I would've seen that being set in:

```
strace -s 128 -v -e trace=process gometalinter --disable-all --enable=megacheck
execve("/home/bradleyf/go/bin/gometalinter", [
"gometalinter", 
"--disable-all", 
"--enable=megacheck"], 
["MANPATH=/opt/rh/rh-git29/root/usr/share/man:", 
"SSH_AGENT_PID=18743", 
"XDG_SESSION_ID=173", 
"HOSTNAME=srv4.teambrad.net", 
"SELINUX_ROLE_REQUESTED=", 
"TERM=screen-256color", 
"SHELL=/bin/bash", 
"HISTSIZE=1000", 
"SSH_CLIENT=202.136.109.227 35384 22", 
"PERL5LIB=/opt/rh/rh-git29/root/usr/share/perl5/vendor_perl", 
"SELINUX_USE_CURRENT_RANGE=", 
"OLDPWD=/home/bradleyf/go/src/github.com/shurcooL/cmd", 
"SSH_TTY=/dev/pts/0", "CDPATH=:/home/bradleyf/go/src/github.com/bradleyfalzon/:/home/bradleyf/go/src/gitlab.com/bradleyfalzon/", 
"USER=bradleyf", 
"LD_LIBRARY_PATH=/opt/rh/httpd24/root/usr/lib64", "LS_COLORS=rs=0:di=38;5;27:ln=38;5;51:mh=44;38;5;15:pi=40;38;5;11:so=38;5;13:do=38;5;5:bd=48;5;232;38;5;11:cd=48;5;232;38;5;3:or="..., 
"DRONE_TOKEN=.."..., 
"SSH_AUTH_SOCK=/tmp/ssh-oLd9ot3Excck/agent.18741", 
"MAIL=/var/spool/mail/bradleyf", 
"PATH=/usr/local/google-cloud-sdk/bin:/home/bradleyf/vim8/bin/:/opt/rh/rh-git29/root/usr/bin:/usr/local/bin:/usr/bin:/usr/local/s"..., "PWD=/home/bradleyf/go/src/github.com/bradleyfalzon/gopherci", 
"LANG=en_AU.UTF-8", 
"SELINUX_LEVEL_REQUESTED=", 
"HISTCONTROL=ignoredups", 
"SHLVL=1", 
"HOME=/home/bradleyf", 
"LOGNAME=bradleyf", 
"DRONE_SERVER=https://drone.teambrad.net/", 
"SSH_CONNECTION=xxx", 
"GOPATH=/home/bradleyf/go", 
"LESSOPEN=||/usr/bin/lesspipe.sh %s", 
"XDG_RUNTIME_DIR=/run/user/1000", 
"_=/usr/bin/strace"]) = 0
```

You're right, setting that flag bring in the checks to the same speed. But I like that hack, will consider it for myself.

I'll check out the CI failure in the next couple days. Did you want other changes made too?

**Comment by alecthomas** [comment]
I do have a question: is there any real reason to include the other linters now that megacheck supersedes them? I feel like duplicating them could cause confusion, particularly with `--enable-all`.

**Comment by bradleyfalzon** [comment]
A cursory thought, I think we could remove them. Should I then?

**Comment by bradleyfalzon** [comment]
Would need to consider people running `gometalinter --disable-all --enable=staticcheck`, a naive removal would break that behaviour.

**Comment by dominikh** [comment]
I would suggest remapping staticcheck, gosimple and unused to pass the appropriate flags to megacheck.

**Comment by bradleyfalzon** [comment]
Yeah, that's what I was thinking, but in practice, this may be a more substantial refactor.

**Comment by bradleyfalzon** [comment]
OK, recent rebase fixes CI.

**Comment by bradleyfalzon** [comment]
Yeah @alecthomas do you have any thoughts on exactly how you want to handle removing staticcheck, gosimple and unused into the one linter?

Further, megacheck doesn't make it clear which tool triggered the issue (doesn't say gosimple, staticcheck or unused) - but it does mention the violation ID numbers which you derive the tool name, eg:

```
gometalinter --disable-all --enable=megacheck

directives.go:147:27:warning: func (*directiveParser).in is unused (U1000) (megacheck)
main.go:30:2:warning: const Warning is unused (U1000) (megacheck)
main.go:821:2:warning: redundant return statement (S1027) (megacheck)
```

When the tools are run individually:

```
gometalinter --disable-all --enable=staticcheck --enable=unused --enable=gosimple

directives.go:147:27:warning: func (*directiveParser).in is unused (U1000) (unused)
main.go:30:2:warning: const Warning is unused (U1000) (unused)
main.go:821:2:warning: redundant return statement (S1027) (gosimple)
```

Is this behaviour going to be OK? @dominikh is this something megacheck could consider adding to the output?

**Comment by dominikh** [comment]
@bradleyfalzon Eventually, there'll be JSON output and we'll include the checker name in that. For the human-readable output, however, we'll stick to only printing the check IDs. As you said, you can derive the checker name from the IDs.

**Comment by alecthomas** [comment]
> this may be a more substantial refactor

This should work: replace the `staticcheck` entry in `linterDefinitions` with the corresponding `megacheck` entry.

> Is this behaviour going to be OK?

I don't think that is a big deal.

Stepping back, I think this is what we want to do:

1. Add megacheck (done).
2. Replace existing gosimple, staticheck and unused  with their megacheck equivalents, but disable them by default.
3. Update 
3. Emit a warning iff gosimple, staticheck AND unused are all enabled, but megacheck is disabled.
4. If megacheck, gosimple, staticcheck AND unused are all enabled, disable the individual linters and emit a warning.

**Comment by bradleyfalzon** [comment]
OK, I've implemented some of this.

> Replace existing gosimple, staticheck and unused with their megacheck equivalents, but disable them by default.

I didn't do this, I ran out of time, do you still want this done, it'd remove a few lines of code from vendor but I think that's about all.

> Emit a warning iff gosimple, staticheck AND unused are all enabled, but megacheck is disabled.

I didn't do this as, (I ran out of time and) in the real world it seemed unlikely someone would run `gometalinter --disable-all --enable=staticcheck --enable=gosimple --enable=unused --disable=megacheck` but let me know if there's other scenarios where this may happen and I can revise.

But further to this, I didn't actually expect this to work, but I didn't look too far into this either:

```
gometalinter --disable-all --enable=staticcheck --enable=gosimple --enable=unused --disable=megacheck
WARNING: staticcheck, gosimple, and unused are all set, using megacheck instead
directives.go:147:27:warning: func (*directiveParser).in is unused (U1000) (megacheck)
main.go:30:2:warning: const Warning is unused (U1000) (megacheck)
main.go:854:2:warning: redundant return statement (S1027) (megacheck)
```

> If megacheck, gosimple, staticcheck AND unused are all enabled, disable the individual linters and emit a warning.

Done.

The one other optimisation would be if someone enabled megacheck (it's on by default) and enabled staticcheck OR gosimple OR unused. I didn't bother checking for this as they'll see the duplicates, but I can add more conditions if you think it'd be valuable.

```
gometalinter --enable=unused | grep '(unused\|megacheck)'
directives.go:147:27:warning: func (*directiveParser).in is unused (U1000) (unused)
main.go:30:2:warning: const Warning is unused (U1000) (unused)
directives.go:147:27:warning: func (*directiveParser).in is unused (U1000) (megacheck)
main.go:30:2:warning: const Warning is unused (U1000) (megacheck)
main.go:854:2:warning: redundant return statement (S1027) (megacheck)
```

**Comment by bradleyfalzon** [comment]
bump @alecthomas

**Comment by alecthomas** [comment]
> I didn't do this as, (I ran out of time and) in the real world it seemed unlikely someone would run gometalinter --disable-all --enable=staticcheck --enable=gosimple --enable=unused --disable=megacheck but let me know if there's other scenarios where this may happen and I can revise.

This is quite likely actually, but if your current warning seems to catch it then I'm fine with that!

> The one other optimisation would be if someone enabled megacheck (it's on by default) and enabled staticcheck OR gosimple OR unused. I didn't bother checking for this as they'll see the duplicates, but I can add more conditions if you think it'd be valuable.

Good point, not a bad idea.

Also, it might be good to warn that the other checks will be removed in the future. Perhaps emit this if any of them are enabled.

**Comment by alecthomas** [comment]
PS. Sorry for the delay, I've been moving house and am now travelling to SF for work.

**Comment by alecthomas** [comment]
If you can fix the merge conflicts, I'll merge this.

**Comment by bradleyfalzon** [comment]
Will do in next 6 hours then

**Comment by bradleyfalzon** [comment]
OK, I see why there was a conflict. #302 was created and merged a few hours ago to address a panic in gosimple, a part of this PR was to update all those linters before adding megacheck - this is where the conflict was I had updated the same packages as that PR.

The conflict wasn't too bad because #302 only updated a single library in go-tools - this isn't the correct approach, go-tools is a monorepo, all packages in the repo must be updated if any of them are. My origin commit (removed because of the conflict) gives the correct instructions on how to update go-tools, repeated here: `cd _linters; grep importpath src/manifest  | egrep -o 'honnef.co/go/tools/[^"]*' | xargs -n 1 gvt update`

So for future reference, use the above command to update go-tools. Because of the conflict, I'd removed my updating commit, and have added a new one updating all the packages to be consistent.

**Comment by dnephin** [comment]
> this isn't the correct approach, go-tools is a monorepo, all packages in the repo must be updated if any of them are

Why do you say that all packages must be updated at the same time?  I am aware it is a monorepo, but I didn't see a reason to update anything except for the package with the fix.

I know some of the other golang dependency management tools enforce this, but it doesn't seem to be necessary (or convenient) with `gvt`.

**Comment by bradleyfalzon** [comment]
> Why do you say that all packages must be updated at the same time?

Previously the tools themselves were split into different repositories, https://github.com/dominikh/go-simple, https://github.com/dominikh/go-staticcheck and https://github.com/dominikh/go-unused - and they all used https://github.com/dominikh/go-lint to share some functionality.

The issue with this, is that an update to go-lint package could be inconsistently applied to users, for example, making a breaking change in go-lint and wanting all tools to update atomically was impossible. Even human errors caused issues https://github.com/dominikh/go-simple/pull/16#issuecomment-235155538

So, Dominik combined all the repos into a monorepo, breaking changes as long as they're applied in the same commit aren't breaking anymore because all dependencies can be updated atomically. So updating the lint package involves updating all tools at the same time.

That's why we should treat it as a monorepo, if we update go-simple, we should update all packages in the git repository. Specifically, when we updated the ssa package in #302, it could have brought a breaking change which required the other tools in the same repository to also require an update.

**Comment by alecthomas** [comment]
Thanks a lot for doing this @bradleyfalzon, I appreciate it. I think this, combined with @dnephin 's change will vastly improve the performance of gometalinter!

**Comment by bradleyfalzon** [comment]
You're welcome, and also thank you @dnephin.

**Pull request merged**
