### PR TITLE
Use a fork of `go tool vet` to fix mutli-package directories

### LINKED ISSUE #351: vet linter fails when run against a directory with multiple packages
Two packages per directory is a common way of providing `example_test.go` for godoc examples, so that the examples can import the package as a user would:
 * https://github.com/gotestyourself/gotestyourself/tree/master/fs has both `fs` and `fs_test` package
 * https://github.com/decred/dcrutil/tree/master/bloom has both `bloom` and `bloom_test` packages

`go vet` fails on these directories because it is called with `*.go` and from the vet docs:

> vets the files named, all of which must be in the same package.

Unfortunately the other argument options (directory, and package path) are not acceptable because they are recursive or don't support shadow (respectively).

The current workaround is to [exclude `example_test.go` ](https://github.com/gotestyourself/gotestyourself/blob/master/gometalinter.json#L5) however that means that the examples will not be linted at all.

The only solution I see to this problem is to fork `go vet`, add a `--no-recursive` flag, and use that fork as the vendoered linter for `vet` and `vetshadow`.

### PR DESCRIPTION
**Pull request by dnephin**
Fixes #351

Uses a govet fork with this patch https://github.com/dnephin/govet/commit/4a96d43e39d340b63daa8bc5576985aa599885f6

This seems to fix the issue for me on the gotestyourself project.

### CODE REVIEW

**Comment by alecthomas** [comment]
:(

Unfortunate. Are you going to attempt to get this patch merged upstream?

**Comment by dnephin** [comment]
Ya, I'll try. Opened https://github.com/golang/go/issues/22296 and https://go-review.googlesource.com/c/go/+/71170

**Comment by dnephin** [comment]
https://github.com/golang/go/issues/22296#issuecomment-336958441

It sounds like maybe this issue has been fixed as of go v1.9.  We should be able to use `go vet -shadow`.

**Comment by dnephin** [comment]
You'll have to install the forked `govet`, which is automatically installed if you use `gometalinter --install`.

**Comment by dpastoor** [comment]
kk testing now...

**Comment by dpastoor** [comment]
thanks for the tip - it works now 👍

**Comment by dpastoor** [comment]
for those that run into this PR just added

```diff
+ - gometalinter --install
  - gometalinter --disable-all -E vet -E gofmt -E misspell -E ineffassign -E goimports -E deadcode --tests --vendor ./...
```

in the script section for travis

**Pull request merged**
