### PR TITLE
add --{exclude,include}-from options

### PR DESCRIPTION
**Pull request by mmlb**

### CODE REVIEW

**Comment by alecthomas** [comment]
Unless there's something I'm missing, I think it's preferable to just use regex alternation:

```
--exclude='foo|bar|waz'
```

**Comment by alecthomas** [comment]
PS. Thanks for the PR though, I always appreciate it when people send code!

**Comment by alecthomas** [comment]
PPS. The command line parse also supports loading flags from files. eg. `gometalinter @gometalinter.flags`

**Comment by mmlb** [comment]
Yeah, I wanted to be very specific with my excluded errors so that I don't exclude something I didn't mean to by mistake for lots of golint warnings mostly, while also not having a crazy command line invocation. I'll take a look at `@gometalinter.flags`.

**Pull request closed without merging**
