### PR TITLE
Aggregate lines

### LINKED ISSUE #117: Deduplicate output
When running on invalid code (that doesn't typecheck or has syntax errors), most tools will output the same error, For example:

```
$ gometalinter               
somefile.go:1:1:warning: expected 'package', found 'IDENT' gibberish (golint)
somefile.go:1:1:warning: expected 'package', found 'IDENT' gibberish (gosimple)
somefile.go:1:1:warning: expected 'package', found 'IDENT' gibberish (staticcheck)
```

This will cause editors to display multiple errors for a line of code. It would be great if gometalinter could coalesce these errors into a single one. Either something like this:

```
somefile.go:1:1:warning: expected 'package', found 'IDENT' gibberish (golint, gosimple, staticcheck)
```

or even without the list of linters at the end.

### PR DESCRIPTION
**Pull request by casimir**
Hi, this PR adds an option that aggregate duplicate messages of the same issue (reported by several linters), it intends to fix #117. Like `--sort`, `--aggregate` can't stream the issues and is an opt-in. It is also compatible with `--sort`.
Two issues are considered equals if the same message is reported for the same location. See examples below.

```
% ls
test.go
% cat test.go
package main

func main() {
    println(("hey")
}
% gometalinter --sort line
test.go:4:20:warning: error return value not checked (missing ',' before newline in argument list (and 1 more errors)) (errcheck)
test.go:4:20:warning: unused global variable missing ',' before newline in argument list (and 1 more errors) (varcheck)
test.go:4:20:error: missing ',' before newline in argument list (gotype)
vet: test.go: test.go:4::error: 20: missing ',' before newline in argument list (and 1 more errors) (vet)
test.go:4:20:warning: missing ',' before newline in argument list (and 1 more errors) (interfacer)
test.go:4:20:warning: missing ',' before newline in argument list (and 1 more errors) (unconvert)
test.go:4:20:warning: missing ',' before newline in argument list (and 1 more errors) (aligncheck)
test.go:4:20:warning: missing ',' before newline in argument list (and 1 more errors) (deadcode)
test.go:4:20:warning: missing ',' before newline in argument list (and 1 more errors) (gosimple)
test.go:4:20:warning: missing ',' before newline in argument list (and 1 more errors) (staticcheck)
test.go:4:20:warning: unused struct field missing ',' before newline in argument list (and 1 more errors) (structcheck)
test.go:4:20:warning: missing ',' before newline in argument list (and 1 more errors) (golint)
vet: test.go: test.go:4::warning: 20: missing ',' before newline in argument list (and 1 more errors) (vetshadow)
test.go:5:3:error: expected '}', found 'EOF' (gotype)
test.go:5:3:error: expected ';', found 'EOF' (gotype)
test.go:5:3:error: expected ';', found 'EOF' (gotype)
test.go:5:3:error: expected ')', found 'EOF' (gotype)
test.go:5:1:error: expected operand, found '}' (gotype)
test.go:5:3:error: missing ',' in argument list (gotype)
% gometalinter --aggregate --sort line
test.go:4:20:warning: unused struct field missing ',' before newline in argument list (and 1 more errors) (structcheck)
test.go:4:20:warning: error return value not checked (missing ',' before newline in argument list (and 1 more errors)) (errcheck)
test.go:4:20:warning: missing ',' before newline in argument list (and 1 more errors) (aligncheck, deadcode, golint, gosimple, interfacer, staticcheck, unconvert)
test.go:4:20:warning: unused global variable missing ',' before newline in argument list (and 1 more errors) (varcheck)
vet: test.go: test.go:4::warning: 20: missing ',' before newline in argument list (and 1 more errors) (vet, vetshadow)
test.go:4:20:error: missing ',' before newline in argument list (gotype)
test.go:5:3:error: expected ';', found 'EOF' (gotype, gotype)
test.go:5:3:error: expected '}', found 'EOF' (gotype)
test.go:5:3:error: missing ',' in argument list (gotype)
test.go:5:1:error: expected operand, found '}' (gotype)
test.go:5:3:error: expected ')', found 'EOF' (gotype)
```

@dominikh was it what you had in mind ?

NB: While the first commit is unrelated with the new option it allows to tests with a fork of this package. I can remove it if it's a problem.

### CODE REVIEW

**Comment by alecthomas** [comment]
Making tests work with forks is a good idea, however the tests are failing on CI.

**Comment by dominikh** [comment]
As far as the output goes, yeah, it matches what I had in mind, thanks.

> NB: While the first commit is unrelated with the new option it allows to tests with a fork of this package. I can remove it if it's a problem

I recommend reading http://blog.campoy.cat/2014/03/github-and-go-forking-pull-requests-and.html to make this kind of modification unnecessary.

**Comment by casimir** [comment]
Forgot to add the source file in `support.go`. My bad.

**Comment by casimir** [comment]
Thanks.

**Pull request merged**
