### PR TITLE
Some linters support a "-t" flag for enabling linting of test code. This PR adds that flag and forwards it to the appropriate linters.

### PR DESCRIPTION
**Pull request by tylerb**

### CODE REVIEW

**Comment by alecthomas** [comment]
Great idea, I hadn't thought of that. Would you mind squashing into one commit?

**Comment by tylerb** [comment]
I'm afraid I have no idea how to do that.

**Comment by tylerb** [comment]
Ok I think that did it. Please confirm and let me know if I need to fix it.

**Comment by alecthomas** [comment]
That's perfect, thanks! I've merged this in.

**Comment by tylerb** [comment]
Wonderful! Thank you!

**Pull request closed without merging**
