### PR TITLE
Use upstream packages

### PR DESCRIPTION
**Pull request by tamird**
@alecthomas the upstream packages seem to be more recent than the forks - what do you think?

### CODE REVIEW

**Comment by alecthomas** [comment]
The gocyclo fork removes recursion.  Without that it is basically unusable in some situations.

The errcheck fork does look like it can be removed though.

**Comment by tamird** [comment]
what's the problem with recursion in gocyclo?

**Comment by alecthomas** [comment]
If you use vendoring (eg. Godeps) it will recursively check every single package in the vendor tree.

**Comment by tamird** [comment]
but if you don't vendor - won't it ignore some of the files in your package?

**Comment by alecthomas** [comment]
Not if you use ./... Which gometalinter handles itself.

**Comment by tamird** [comment]
:( looks like there are more serious problems with gometalinter - defercheck, errcheck, varcheck, go vet all seem to categorically fail when run by gometalinter.

**Comment by alecthomas** [comment]
Those linters recently changed their output format and gometalinter was updated accordingly. You will need to run gometalinter-i -u

**Comment by alecthomas** [comment]
Go vet works for me though. If you run with --debug it will show all output.

**Comment by tamird** [comment]
I installed and update all packages to no avail - I think I'm just going to stick to a makefile.

**Comment by alecthomas** [comment]
If you try that latest commit it may help with vet and varcheck. It would be really helpful to get --debug output to find out why defercheck and errcheck don't work.

**Pull request closed without merging**
