### PR TITLE
Update errcheck to e96dacdb078a5166c20b48dd667fb26d2ce0379

### PR DESCRIPTION
**Pull request by yasushi-saito**
It contains useful updates, including suppressing warnings for Write
implementations that will never fail.

### CODE REVIEW

**Comment by alecthomas** [comment]
Thanks!

**Comment by lkysow** [comment]
I think this has caused `errcheck` to start erroring on `fmt` functions that it didn't error on before, ex:
```
server/events_controller.go:170:15:warning: error return value not checked (fmt.Fprintln(w, "Processing...")) (errcheck)
```

According to its docs, it should be ignoring these by default: 
> Note that by default the fmt package is ignored entirely, unless a regex is specified for it.

https://github.com/kisielk/errcheck

**Comment by alecthomas** [comment]
Mmm, yep, seems like an upstream problem :\

I'll roll it back.

**Comment by alecthomas** [comment]
Actually I can't find that in the README anymore, and it seems this is deliberate:

https://github.com/kisielk/errcheck/issues/140

**Comment by alecthomas** [comment]
Which seems reasonable to me, so I will probably re-merge this change.

**Comment by lkysow** [comment]
It's here: https://github.com/kisielk/errcheck/blame/master/README.md#L87

But yes, I think gometalinter should just use the upstream version. I just need to find a way to disable that in my running of it (and probably a lot of people).

**Comment by lkysow** [comment]
For anyone else running into this that wants to disable `errcheck` and `fmt:.*` I had to create a `.gometalinter.json` file because to disable checking `fmt` you need to use the command `errcheck -ignore 'fmt:.*'` but you can't specify that as a flag to `gometalinter` because it uses the `:` as a delimiter itself.

Also if you're using a config file and you want to modify how a linter runs you need to add a `Linters` key, which only works if you also have an `Enabled` key for that linter, which means you need to explicitly enable all the default linters.

My final config file which you will probably want to tweak:
```json
{
  "Disable": ["gotype", "gotypex", "maligned", "gocyclo", "golint"],
  "Enable": [
    "gas",
    "errcheck",
    "deadcode",
    "gochecknoinits",
    "goconst",
    "gocyclo",
    "gofmt",
    "goimports",
    "golint",
    "gotype",
    "gotypex",
    "ineffassign",
    "interfacer",
    "maligned",
    "megacheck",
    "safesql",
    "structcheck",
    "test",
    "testify",
    "unconvert",
    "unparam",
    "varcheck",
    "vet",
    "vetshadow"
  ],
  "Deadline": "300s",
  "Vendor": true,
  "LineLength": 120,
  "Skip": ["server/static", "mocks"],
  "WarnUnmatchedDirective": true,
  "Linters": {
    "gas": "gas -exclude=G104 -fmt=csv:^(?P<path>.*?\\.go),(?P<line>\\d+),(?P<message>[^,]+,[^,]+,[^,]+)",
    "errcheck": {
      "Command": "errcheck -abspath -ignore 'fmt:.*'",
      "Pattern": "PATH:LINE:COL:MESSAGE",
      "PartitionStrategy": "packages"
    }
  }
}

```

**Comment by alecthomas** [comment]
Did you try - - exclude?

**Comment by lkysow** [comment]
No I didn't actually. Thinking about it now that would work but it would be more inexact than using errcheck's `-ignore` flag because if you excluded `.*fmt\..*\;(errcheck\(` then you might miss a one-liner like:
```
myFuncThatReturnsErr(fmt.Sprintf("%s", "string"))
```

**Pull request merged**
