### PR TITLE
Update Atom linter URL

### PR DESCRIPTION
**Pull request by emead**

### CODE REVIEW

**Comment by alecthomas** [comment]
I don't think this replaces the linter plugin does it? Can you add a line rather than replace?

**Comment by emead** [comment]
The link which is currently in the README doesn't work (although gometalinter-linter is still on github: https://github.com/joefitzgerald/gometalinter-linter).

go-plus is owned by the same author and includes gometalinter functionality.

I don't actually use Atom. Perhaps @joefitzgerald can clarify.

**Comment by joefitzgerald** [comment]
Yes this should be updated to point to go-plus. Thanks for catching that.

**Comment by joefitzgerald** [comment]
Just to clarify: yes this does replace the line; the go-plus package includes the functionality that was previously in a separate package.

**Comment by alecthomas** [comment]
Aha, ok, thanks then @emead !

**Pull request merged**
